export const allTextureKeys = {
	back: 'back',
	bubbleOne: 'bubbleOne',
	bubbleTwo: 'bubbleTwo',
	bubbleThree: 'bubbleThree',
	build: 'build',
	circularSaw: 'circularSaw',
	coin: 'coin',
	cure: 'cure',
	free: 'free',
	gem: 'gem',
	getProfit: 'getProfit',
	goldenChestClosed: 'goldenChestClosed',
	goldenChestOpen: 'goldenChestOpen',
	hand: 'hand',
	handTap: 'handTap',
	installButton: 'installButton',
	ironChestClosed: 'ironChestClosed',
	ironChestOpen: 'ironChestOpen',
	logo: 'logo',
	mine: 'mine',
	oreOne: 'oreOne',
	oreTwo: 'oreTwo',
	oreThree: 'oreThree',
	oreFour: 'oreFour',
	pickaxe: 'pickaxe',
	shadow: 'shadow',
	shine: 'shine',
	shineGold: 'shineGold',
	siedgeHammer: 'siedgeHammer',
	smoke: 'smoke',
	woodenChestClosed: 'woodenChestClosed',
	woodenChestOpen: 'woodenChestOpen',
};

export const appTextures = {
	[allTextureKeys.back]: 'img/back.webp',
	[allTextureKeys.bubbleOne]: 'img/bubble1.webp',
	[allTextureKeys.bubbleTwo]: 'img/bubble2.webp',
	[allTextureKeys.bubbleThree]: 'img/bubble3.webp',
	[allTextureKeys.build]: 'img/build.webp',
	[allTextureKeys.circularSaw]: 'img/circularsaw.webp',
	[allTextureKeys.coin]: 'img/coin.webp',
	[allTextureKeys.cure]: 'img/cure.webp',
	[allTextureKeys.free]: 'img/free.webp',
	[allTextureKeys.gem]: 'img/gem.webp',
	[allTextureKeys.getProfit]: 'img/getProfit.webp',
	[allTextureKeys.goldenChestClosed]: 'img/goldenChestClosed.webp',
	[allTextureKeys.goldenChestOpen]: 'img/goldenChestOpen.webp',
	[allTextureKeys.hand]: 'img/hand.webp',
	[allTextureKeys.handTap]: 'img/handTap.webp',
	[allTextureKeys.installButton]: 'img/install_btn.webp',
	[allTextureKeys.ironChestClosed]: 'img/ironChestClosed.webp',
	[allTextureKeys.ironChestOpen]: 'img/ironChestOpen.webp',
	[allTextureKeys.logo]: 'img/logo.webp',
	[allTextureKeys.mine]: 'img/mine.webp',
	[allTextureKeys.oreOne]: 'img/ore1.webp',
	[allTextureKeys.oreTwo]: 'img/ore2.webp',
	[allTextureKeys.oreThree]: 'img/ore3.webp',
	[allTextureKeys.oreFour]: 'img/ore4.webp',
	[allTextureKeys.pickaxe]: 'img/pickaxe.webp',
	[allTextureKeys.shadow]: 'img/shadow.webp',
	[allTextureKeys.shine]: 'img/shine.webp',
	[allTextureKeys.shineGold]: 'img/shineGold.webp',
	[allTextureKeys.shineGold]: 'img/shineGold.webp',
	[allTextureKeys.siedgeHammer]: 'img/siedgehammer.webp',
	[allTextureKeys.smoke]: 'img/smoke.webp',
	[allTextureKeys.woodenChestClosed]: 'img/woodenChestClosed.webp',
	[allTextureKeys.woodenChestOpen]: 'img/woodenChestOpen.webp',
};
export const audioAssets = {
	build: 'audio/build.mp3',
	buildTwo: 'audio/build2.mp3',
	music: 'audio/music.mp3',
	swoosh: 'audio/swoosh.mp3',
};
