export const labels = {
	game: 'game',
	fingerContainer:  'fingerContainer',
	finger:  'finger',
	fingerActive:  'fingerActive',
	sceneFinish: 'sceneFinish',
	button: 'button',
	bg: 'bg',
	label: 'label',
	installButton: 'installButton',
	resourceBars: 'resourceBars',
	moneyBar: 'moneyBar',
	diamondBar: 'diamondBar',
	potionBar: 'potionBar',
	textMerge: 'textMerge',
	goblins: 'goblins',
	goblinContainer: 'goblinContainer',
	goblin: 'goblin',
	upgradeGoblin: 'upgradeGoblin',
	goblinOne: 'goblinOne',
	goblinTwo: 'goblinTwo',
	ore: 'ore',
	coin: 'coin',
	gem: 'gem',
	cure: 'cure',
	shadow:  'shadow',
	chest: 'chest',
	chestOpen: 'chestOpen',
	chests: 'chests',
	mine: 'mine',
	smoke: 'smoke',
	gameSceneStart: 'gameSceneStart',
	gameSceneMove: 'gameSceneMove',
	gameSceneFinish: 'gameSceneFinish',
};

export const elementType = {
	SPRITE: 'sprite',
	CONTAINER: 'container',
	TEXT: 'text',
	GRAPHICS: 'graphics',
	ANIMATED_SPRITE: 'animation',
};
