export const labels = {
	game: 'game',
	finger:  'finger',
	sceneFinish: 'sceneFinish',
	button: 'button',
	bg: 'bg',
	label: 'label',
	installButton: 'installButton',
	resourceBars: 'resourceBars',
	moneyBar: 'moneyBar',
	diamondBar: 'diamondBar',
	potionBar: 'potionBar',
	textMerge: 'textMerge',
	goblins: 'goblins',
	goblinContainer: 'goblinContainer',
	goblinOne: 'goblinOne',
	goblinTwo: 'goblinTwo',
	goblinThree: 'goblinThree',
	goblinFour: 'goblinFour',
	goblinFive: 'goblinFive',
	ore: 'ore',
	coin: 'coin',
};

export const elementType = {
	SPRITE: 'sprite',
	CONTAINER: 'container',
	TEXT: 'text',
	GRAPHICS: 'graphics',
	ANIMATED_SPRITE: 'animation',
};
